// auto_wiki_rebuild.cjs — PostToolUse hook for Edit/Write/MultiEdit
//
// Detects edits to files that should trigger a wiki rebuild:
//   - research_archive/doc_references/**.md   (new/modified paper fiches)
//   - research_archive/discoveries/**.md       (D-series, C-series, TRIPLE_*)
//   - research_archive/_staging/briefings/**.md (director briefings)
//   - research_archive/_staging/memory/MEMORY_STATE.md
//   - research_archive/_staging/audit-these/**.md
//   - wiki/docs/**.md (manual wiki edits)
//   - wiki/mkdocs.yml (nav changes)
//   - wiki/build_wiki.py (pipeline changes)
//
// When triggered, it:
//   1. Writes a marker file `.claude/.wiki_rebuild_pending` with the timestamp
//   2. If throttle (30s) has elapsed since last rebuild, spawns the rebuild
//      in background via `node` detached process, logs to `.claude/logs/wiki_rebuild.log`
//   3. Otherwise just updates the marker — the next matching edit after 30s will trigger
//
// The hook never blocks the tool call — it returns exit 0 silently. Rebuild
// failures are surfaced in the log file only. Manual rebuild is always
// available via `/wiki-publish update` or `python wiki/build_wiki.py`.
//
// Triggered by: Claude Code PostToolUse on Edit, Write, MultiEdit
// Added: PDCA cycle 3, RETEX 2026-04-11 (bibliography-maintainer pipeline
// leaves _staging/briefings stale in the wiki until manual /wiki-publish).

const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const MARKER_FILE = path.join(REPO_ROOT, '.claude', '.wiki_rebuild_pending');
const LAST_RUN_FILE = path.join(REPO_ROOT, '.claude', '.wiki_rebuild_last');
const LOG_DIR = path.join(REPO_ROOT, '.claude', 'logs');
const LOG_FILE = path.join(LOG_DIR, 'wiki_rebuild.log');

// Throttle: minimum seconds between two rebuilds (debounce rapid edits)
const THROTTLE_SECONDS = 30;

// Paths that, when modified, should trigger a rebuild
const TRIGGER_PATTERNS = [
  /^research_archive\/doc_references\/.+\.md$/,
  /^research_archive\/discoveries\/.+\.md$/,
  /^research_archive\/_staging\/briefings\/.+\.md$/,
  /^research_archive\/_staging\/memory\/MEMORY_STATE\.md$/,
  /^research_archive\/_staging\/audit-these\/.+\.md$/,
  /^research_archive\/_staging\/research-director\/.+\.md$/,
  /^research_archive\/manuscript\/[^/]+\.md$/,  // only top-level manuscript, not docx
  /^wiki\/docs\/[^/]+\.md$/,
  /^wiki\/docs\/.+\/[^/]+\.md$/,
  /^wiki\/docs\/javascripts\/.+\.js$/,
  /^wiki\/docs\/stylesheets\/.+\.css$/,
  /^wiki\/mkdocs\.yml$/,
  /^wiki\/build_wiki\.py$/,
];

// Paths to ignore (auto-generated by build_wiki.py — don't loop!)
const IGNORE_PATTERNS = [
  /^wiki\/docs\/research\/bibliography\/\d{4}\//,  // auto-generated year dirs
  /^wiki\/docs\/research\/fiches-attaque\//,
  /^wiki\/docs\/prompts\/.+\.md$/,
  /^wiki\/docs\/experiments\/retex\//,  // auto-copied from _staging
  /^wiki\/docs\/staging\//,  // auto-copied
  /^wiki\/nav_generated\.yml$/,
  /^wiki\/site\//,  // mkdocs build output
];

function normalizePath(p) {
  if (!p) return '';
  // Strip repo root prefix if present, normalize separators
  let rel = p.replace(/\\/g, '/');
  const rootNorm = REPO_ROOT.replace(/\\/g, '/');
  if (rel.startsWith(rootNorm)) {
    rel = rel.slice(rootNorm.length).replace(/^\//, '');
  }
  return rel.replace(/^\.\//, '');
}

function shouldTrigger(relPath) {
  if (!relPath) return false;
  if (IGNORE_PATTERNS.some((re) => re.test(relPath))) return false;
  return TRIGGER_PATTERNS.some((re) => re.test(relPath));
}

function ensureLogDir() {
  try {
    if (!fs.existsSync(LOG_DIR)) {
      fs.mkdirSync(LOG_DIR, { recursive: true });
    }
  } catch (e) {
    // ignore
  }
}

function logLine(msg) {
  ensureLogDir();
  const ts = new Date().toISOString();
  const line = `[${ts}] ${msg}\n`;
  try {
    fs.appendFileSync(LOG_FILE, line, 'utf8');
  } catch (e) {
    // ignore — never block tool call on log failure
  }
}

function getLastRunTs() {
  try {
    if (!fs.existsSync(LAST_RUN_FILE)) return 0;
    const v = parseInt(fs.readFileSync(LAST_RUN_FILE, 'utf8').trim(), 10);
    return Number.isFinite(v) ? v : 0;
  } catch (e) {
    return 0;
  }
}

function setLastRunTs(ts) {
  try {
    fs.writeFileSync(LAST_RUN_FILE, String(ts), 'utf8');
  } catch (e) {
    // ignore
  }
}

function writeMarker(relPath) {
  try {
    const data = {
      pending: true,
      triggered_by: relPath,
      timestamp: new Date().toISOString(),
    };
    fs.writeFileSync(MARKER_FILE, JSON.stringify(data, null, 2), 'utf8');
  } catch (e) {
    // ignore
  }
}

function clearMarker() {
  try {
    if (fs.existsSync(MARKER_FILE)) fs.unlinkSync(MARKER_FILE);
  } catch (e) {
    // ignore
  }
}

function spawnRebuild(relPath) {
  logLine(`Triggered by ${relPath} — spawning rebuild...`);

  // Windows: use python.exe via powershell; Linux/Mac: use python3
  const isWin = process.platform === 'win32';
  const pythonBin = isWin ? 'python.exe' : 'python3';

  // build_wiki.py first (copies sources), then mkdocs build (generates site)
  const buildScript = path.join(REPO_ROOT, 'wiki', 'build_wiki.py');

  const child = spawn(
    pythonBin,
    [buildScript],
    {
      cwd: path.join(REPO_ROOT, 'wiki'),
      detached: true,
      stdio: ['ignore', 'pipe', 'pipe'],
      windowsHide: true,
    },
  );

  let stdout = '';
  let stderr = '';
  child.stdout.on('data', (data) => { stdout += data.toString(); });
  child.stderr.on('data', (data) => { stderr += data.toString(); });

  child.on('close', (code) => {
    if (code === 0) {
      logLine(`build_wiki.py OK (exit 0)`);
      // Chain mkdocs build
      const mkdocs = spawn(
        pythonBin,
        ['-m', 'mkdocs', 'build'],
        {
          cwd: path.join(REPO_ROOT, 'wiki'),
          detached: true,
          stdio: ['ignore', 'pipe', 'pipe'],
          windowsHide: true,
        },
      );
      let mout = '';
      let merr = '';
      mkdocs.stdout.on('data', (d) => { mout += d.toString(); });
      mkdocs.stderr.on('data', (d) => { merr += d.toString(); });
      mkdocs.on('close', (mcode) => {
        if (mcode === 0) {
          logLine(`mkdocs build OK (exit 0) — rebuild complete for ${relPath}`);
          clearMarker();
        } else {
          logLine(`mkdocs build FAIL (exit ${mcode}): ${merr.slice(0, 500)}`);
        }
      });
      mkdocs.on('error', (err) => {
        logLine(`mkdocs spawn error: ${err.message}`);
      });
      mkdocs.unref();
    } else {
      logLine(`build_wiki.py FAIL (exit ${code}): ${stderr.slice(0, 500)}`);
    }
  });

  child.on('error', (err) => {
    logLine(`python spawn error: ${err.message}`);
  });

  child.unref();
}

function main() {
  // Parse hook payload from stdin (Claude Code PostToolUse convention)
  let payload = '';
  try {
    payload = fs.readFileSync(0, 'utf8');
  } catch (e) {
    process.exit(0);
  }

  if (!payload) process.exit(0);

  let data;
  try {
    data = JSON.parse(payload);
  } catch (e) {
    // Not a JSON payload — nothing to do
    process.exit(0);
  }

  // Extract file path from tool_input (supports Edit, Write, MultiEdit)
  const toolName = data.tool_name || data.tool || '';
  const input = data.tool_input || data.input || {};

  // Only react to successful completions if tool_response is provided
  const resp = data.tool_response || data.response;
  if (resp && resp.success === false) {
    process.exit(0);
  }

  let filePath = '';
  if (toolName === 'Write' || toolName === 'Edit') {
    filePath = input.file_path || '';
  } else if (toolName === 'MultiEdit') {
    filePath = input.file_path || '';
  } else {
    // Not a file edit — skip
    process.exit(0);
  }

  if (!filePath) process.exit(0);

  const rel = normalizePath(filePath);
  if (!shouldTrigger(rel)) {
    process.exit(0);
  }

  // Trigger eligible: check throttle
  const nowSec = Math.floor(Date.now() / 1000);
  const lastSec = getLastRunTs();
  const elapsed = nowSec - lastSec;

  if (elapsed < THROTTLE_SECONDS) {
    // Still in debounce window — just update marker, don't rebuild yet
    writeMarker(rel);
    logLine(
      `DEBOUNCE (${elapsed}s < ${THROTTLE_SECONDS}s) for ${rel} — marker updated, rebuild deferred`,
    );
    process.exit(0);
  }

  // Record intent and spawn rebuild
  setLastRunTs(nowSec);
  writeMarker(rel);
  spawnRebuild(rel);
  process.exit(0);
}

try {
  main();
} catch (e) {
  // Never block the tool call on hook failure
  try {
    logLine(`HOOK ERROR: ${e.message}`);
  } catch (_) {}
  process.exit(0);
}
