"""
LLM Providers Routes — Multi-LLM Testing Interface for PromptForge
Handles configuration, health checks, and prompt testing across multiple LLM providers.
"""

import json
import os
import asyncio
import time
from typing import Optional, List, Dict, Any
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import logging

# Configure logging
logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/redteam", tags=["llm-providers"])

# Load provider configuration
CONFIG_PATH = os.path.join(os.path.dirname(__file__), "..", "prompts", "llm_providers_config.json")

def load_provider_config() -> Dict[str, Any]:
    """Load LLM provider configuration from JSON file."""
    try:
        with open(CONFIG_PATH, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        logger.error(f"Config file not found: {CONFIG_PATH}")
        return {"providers": {}}
    except json.JSONDecodeError as e:
        logger.error(f"Invalid JSON in config: {e}")
        return {"providers": {}}

# Request/Response models
class PromptTestRequest(BaseModel):
    provider: str
    model: str
    prompt: str
    temperature: float = 0.7
    max_tokens: int = 1024
    system_prompt: Optional[str] = None

class PromptCompareRequest(BaseModel):
    prompt: str
    system_prompt: Optional[str] = None
    temperature: float = 0.7
    max_tokens: int = 1024
    providers: Optional[List[str]] = None  # If None, use all enabled

class ProviderConfigUpdateRequest(BaseModel):
    enabled: Optional[bool] = None
    api_key: Optional[str] = None
    endpoint_url: Optional[str] = None
    timeout_seconds: Optional[int] = None

# Helper functions
def get_enabled_providers(config: Dict[str, Any]) -> List[str]:
    """Get list of enabled provider names."""
    return [
        name for name, provider in config.get("providers", {}).items()
        if provider.get("enabled", False)
    ]

def validate_provider_exists(config: Dict[str, Any], provider: str) -> bool:
    """Check if provider exists in config."""
    return provider in config.get("providers", {})

def get_provider_api_key(provider: str) -> Optional[str]:
    """Get API key for provider from environment variables."""
    config = load_provider_config()
    provider_config = config.get("providers", {}).get(provider)

    if not provider_config:
        return None

    auth = provider_config.get("auth")
    if not auth:
        return None

    api_key_env = auth.get("api_key_env")
    if not api_key_env:
        return None

    return os.getenv(api_key_env)

async def test_provider_health(provider: str, config_provider: Dict[str, Any]) -> tuple[bool, str]:
    """Test provider connectivity and return (is_healthy, message)."""
    try:
        if provider == "ollama":
            # Simple Ollama health check
            import httpx
            async with httpx.AsyncClient(timeout=5.0) as client:
                host = config_provider.get("host", "http://127.0.0.1:11434")
                health_path = config_provider.get("health_check_path", "/api/tags")
                response = await client.get(f"{host}{health_path}")
                if response.status_code == 200:
                    return True, "OK"
                else:
                    return False, f"HTTP {response.status_code}"
        else:
            # Cloud providers - check if API key is set
            api_key = get_provider_api_key(provider)
            if not api_key:
                return False, "API key not configured"
            return True, "OK"
    except Exception as e:
        return False, str(e)

async def call_llm(
    provider: str,
    model: str,
    prompt: str,
    system_prompt: Optional[str],
    temperature: float,
    max_tokens: int
) -> Optional[str]:
    """
    Call LLM provider and return response.
    Uses the LLM factory to instantiate the correct provider model.
    """
    try:
        from agents.attack_chains.llm_factory import get_llm

        llm = get_llm(
            provider=provider,
            model=model,
            temperature=temperature
        )

        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        # Invoke the LLM with the prompt
        response = llm.invoke(messages)
        return response.content if hasattr(response, 'content') else str(response)
    except Exception as e:
        logger.error(f"Error calling {provider}/{model}: {e}")
        return None


async def stream_llm(
    provider: str,
    model: str,
    prompt: str,
    system_prompt: Optional[str],
    temperature: float,
    max_tokens: int
):
    """
    Stream tokens from LLM provider in real-time.
    Yields individual tokens as they are generated by the model.
    """
    try:
        from agents.attack_chains.llm_factory import get_llm

        llm = get_llm(
            provider=provider,
            model=model,
            temperature=temperature
        )

        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})

        # Stream tokens from the LLM in real-time
        async for chunk in llm.astream(messages):
            # Extract token content from chunk
            token = chunk.content if hasattr(chunk, 'content') else str(chunk)
            if token:
                yield token
    except Exception as e:
        logger.error(f"Streaming error with {provider}/{model}: {e}")
        raise

# ============================================================================
# API ENDPOINTS
# ============================================================================

@router.get("/llm-providers")
async def list_llm_providers(request: Request):
    """
    Get list of available LLM providers and their status.

    Returns list of enabled providers with:
    - name: Human-readable provider name
    - type: 'local' or 'cloud'
    - models: Available models
    - default_model: Default model for this provider
    - status: 'ok' or 'error'
    """
    config = request.app.state.llm_config or load_provider_config()
    providers_list = []

    for provider_name, provider_config in config.get("providers", {}).items():
        if not provider_config.get("enabled", False):
            continue

        is_healthy, health_msg = await test_provider_health(provider_name, provider_config)

        providers_list.append({
            "name": provider_name,
            "display_name": provider_config.get("name", provider_name),
            "type": provider_config.get("type"),
            "models": provider_config.get("models", []),
            "default_model": provider_config.get("default_model"),
            "status": "ok" if is_healthy else "error",
            "status_message": health_msg if not is_healthy else None
        })

    return {
        "providers": providers_list,
        "total": len(providers_list),
        "timestamp": time.time()
    }

@router.get("/llm-providers/{provider}/models")
async def get_provider_models(provider: str, request: Request):
    """Get available models for a specific provider."""
    config = request.app.state.llm_config or load_provider_config()

    if not validate_provider_exists(config, provider):
        raise HTTPException(status_code=404, detail=f"Provider '{provider}' not found")

    provider_config = config["providers"][provider]

    return {
        "provider": provider,
        "models": provider_config.get("models", []),
        "default_model": provider_config.get("default_model")
    }

@router.get("/llm-providers/{provider}/status")
async def get_provider_status(provider: str, request: Request):
    """Check health status of a specific provider."""
    config = request.app.state.llm_config or load_provider_config()

    if not validate_provider_exists(config, provider):
        raise HTTPException(status_code=404, detail=f"Provider '{provider}' not found")

    provider_config = config["providers"][provider]
    start_time = time.time()
    is_healthy, health_msg = await test_provider_health(provider, provider_config)
    latency_ms = int((time.time() - start_time) * 1000)

    return {
        "provider": provider,
        "status": "ok" if is_healthy else "error",
        "message": health_msg,
        "latency_ms": latency_ms,
        "type": provider_config.get("type"),
        "timestamp": time.time()
    }

@router.post("/llm-test")
async def test_single_provider(request: PromptTestRequest):
    """
    Test prompt on a single LLM provider with streaming response.

    Returns Server-Sent Events (SSE) stream with:
    - token: Individual token from the LLM
    - provider: Provider name
    - timestamp: Event timestamp
    """
    config = request.app.state.llm_config or load_provider_config()

    # Validate provider exists and is enabled
    if not validate_provider_exists(config, request.provider):
        raise HTTPException(status_code=404, detail=f"Provider '{request.provider}' not found")

    if not config["providers"][request.provider].get("enabled", False):
        raise HTTPException(status_code=400, detail=f"Provider '{request.provider}' is not enabled")

    async def event_stream():
        """Stream response tokens as SSE events."""
        try:
            start_time = time.time()
            token_count = 0

            # Stream tokens from the LLM in real-time
            async for token in stream_llm(
                provider=request.provider,
                model=request.model,
                prompt=request.prompt,
                system_prompt=request.system_prompt,
                temperature=request.temperature,
                max_tokens=request.max_tokens
            ):
                token_count += 1
                yield f'data: {json.dumps({
                    "token": token,
                    "provider": request.provider,
                    "timestamp": time.time()
                })}\n\n'

            # Final summary
            duration_ms = int((time.time() - start_time) * 1000)
            yield f'data: {json.dumps({
                "type": "complete",
                "duration_ms": duration_ms,
                "tokens": token_count
            })}\n\n'

        except Exception as e:
            logger.error(f"Streaming error: {e}")
            yield f'data: {json.dumps({"error": str(e)})}\n\n'

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive"
        }
    )

@router.post("/llm-compare")
async def compare_providers(request: PromptCompareRequest):
    """
    Test prompt on multiple LLM providers in parallel.

    Returns JSON with results from all enabled providers (or specified providers):
    {
        "results": {
            "ollama": {
                "response": "...",
                "tokens": N,
                "duration_ms": X,
                "status": "ok"|"error"
            },
            ...
        },
        "timestamp": X
    }
    """
    config = request.app.state.llm_config or load_provider_config()

    # Determine which providers to test
    if request.providers:
        providers_to_test = request.providers
    else:
        providers_to_test = get_enabled_providers(config)

    # Validate all providers exist
    for provider in providers_to_test:
        if not validate_provider_exists(config, provider):
            raise HTTPException(status_code=404, detail=f"Provider '{provider}' not found")

    # Test providers in parallel
    tasks = {}
    for provider in providers_to_test:
        if config["providers"][provider].get("enabled", False):
            model = config["providers"][provider].get("default_model")
            tasks[provider] = asyncio.create_task(
                call_llm(
                    provider=provider,
                    model=model,
                    prompt=request.prompt,
                    system_prompt=request.system_prompt,
                    temperature=request.temperature,
                    max_tokens=request.max_tokens
                )
            )

    # Collect results
    results = {}
    for provider, task in tasks.items():
        try:
            start_time = time.time()
            response = await task
            duration_ms = int((time.time() - start_time) * 1000)

            results[provider] = {
                "status": "ok" if response else "error",
                "response": response or "",
                "tokens": len(response) if response else 0,
                "duration_ms": duration_ms
            }
        except Exception as e:
            logger.error(f"Error testing {provider}: {e}")
            results[provider] = {
                "status": "error",
                "response": None,
                "tokens": 0,
                "duration_ms": 0,
                "error": str(e)
            }

    return {
        "results": results,
        "timestamp": time.time()
    }

@router.get("/llm-providers/{provider}/config")
async def get_provider_config(provider: str, request: Request):
    """Get full configuration for a specific provider."""
    config = request.app.state.llm_config or load_provider_config()

    if not validate_provider_exists(config, provider):
        raise HTTPException(status_code=404, detail=f"Provider '{provider}' not found")

    provider_config = config["providers"][provider].copy()

    # Remove sensitive auth info from response
    if "auth" in provider_config:
        auth = provider_config["auth"]
        provider_config["auth"] = {
            "method": auth.get("method"),
            "requires_api_key": bool(auth.get("api_key_env")),
            "configured": bool(os.getenv(auth.get("api_key_env", "")))
        }

    return provider_config

@router.put("/llm-providers/{provider}/config")
async def update_provider_config(provider: str, update: ProviderConfigUpdateRequest, request: Request):
    """
    Update provider configuration.
    Note: API keys should be set via environment variables, not this endpoint.
    """
    config = request.app.state.llm_config or load_provider_config()

    if not validate_provider_exists(config, provider):
        raise HTTPException(status_code=404, detail=f"Provider '{provider}' not found")

    # Only allow updating enabled flag and timeout
    if update.enabled is not None:
        config["providers"][provider]["enabled"] = update.enabled

    if update.timeout_seconds is not None:
        config["providers"][provider]["timeout_seconds"] = update.timeout_seconds

    # Note: In a real implementation, this would persist to database or file
    # For now, changes are in-memory only

    return {
        "status": "updated",
        "provider": provider,
        "changes": {
            "enabled": update.enabled,
            "timeout_seconds": update.timeout_seconds
        }
    }

# Register router
# In server.py: app.include_router(llm_providers_routes.router)
