#!/usr/bin/env python3
"""Build the distributable OMC-AEGIS Claude Code plugin from `.claude/skills/`.

Single source of truth: `.claude/skills/<name>/`. This standalone build tool
regenerates the plugin tree (`skills/`, `commands/`, `.claude-plugin/`) by copying
the core skill directories and emitting dispatch shims + manifests, so the AEGIS
research director can be distributed via `/plugin marketplace add <repo>`.

Layout replicated natively from oh-my-claudecode (MIT) — `.claude-plugin/plugin.json`
+ `commands/*.md` dispatch shims. No OMC code is copied; only the plugin structure
is reproduced. See docs/omc_fusion/INTEGRATION_TRACKER.md.

This is a dev/build CLI: it prints progress to stdout by design (not a server).
It performs no LLM calls, so it does not need `env_loader`.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

PLUGIN_NAME = "omc-aegis"
PLUGIN_VERSION = "0.1.0"

# Director core scope (validated decision: 9 skills, no autopilot/ralph — safety floor S1).
CORE_SKILLS = [
    "research-director",
    "aegis-research-lab",
    "bibliography-maintainer",
    "fiche-attaque",
    "aegis-prompt-forge",
    "aegis-validation-pipeline",
    "experimentalist",
    "experiment-planner",
    "thesis-writer",
]

# Never distribute build caches or local runtime memory (tool_hits.jsonl, etc.).
IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", "*.pyo", "memory", ".DS_Store")

BANNER = (
    "<!-- GENERATED by scripts/build_omc_plugin.py - DO NOT EDIT.\n"
    "     Edit the source skill in .claude/skills/<name>/ and re-run the build. -->\n"
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SKILLS_SRC = PROJECT_ROOT / ".claude" / "skills"
SKILLS_OUT = PROJECT_ROOT / "skills"
COMMANDS_OUT = PROJECT_ROOT / "commands"
PLUGIN_DIR = PROJECT_ROOT / ".claude-plugin"


def copy_skill(name: str) -> None:
    """Copy one source skill dir into the generated plugin tree (faithful copy)."""
    src = SKILLS_SRC / name
    if not src.is_dir():
        raise SystemExit("[ERROR] source skill not found: " + str(src))
    dst = SKILLS_OUT / name
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=IGNORE)
    print("  copied skill: " + name)


def write_command_shim(name: str) -> None:
    """Emit a lightweight dispatch command that defers to the skill's SKILL.md."""
    shim = (
        "---\n"
        'description: ""\n'
        "---\n\n"
        + BANNER
        + "\n# " + name + "\n\n"
        "Compatibility command for `/" + PLUGIN_NAME + ":" + name + "`.\n\n"
        "## Dispatch\n\n"
        "1. Read the full skill instructions: `skills/" + name + "/SKILL.md`.\n"
        "2. Follow that SKILL.md exactly, treating the user's arguments as:\n\n"
        "```text\n$ARGUMENTS\n```\n"
    )
    (COMMANDS_OUT / (name + ".md")).write_text(shim, encoding="utf-8")


def write_plugin_json() -> None:
    """Generate `.claude-plugin/plugin.json` (declarative: skills + commands only)."""
    manifest = {
        "name": PLUGIN_NAME,
        "version": PLUGIN_VERSION,
        "description": (
            "AEGIS autonomous research director for Claude Code - OODA loop, safety "
            "floor, multi-level memory. Generated from .claude/skills/ (single source)."
        ),
        "author": {"name": "AEGIS (poc_medical, ENS 2026)"},
        "license": "MIT",
        "keywords": ["claude-code", "plugin", "research", "orchestration", "llm-security"],
        "skills": ["./skills/" + n + "/" for n in CORE_SKILLS],
        "commands": "./commands/",
    }
    (PLUGIN_DIR / "plugin.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def write_marketplace_json() -> None:
    """Generate `.claude-plugin/marketplace.json` (single-plugin registry)."""
    market = {
        "$schema": "https://anthropic.com/claude-code/marketplace.schema.json",
        "name": PLUGIN_NAME,
        "version": PLUGIN_VERSION,
        "description": (
            "AEGIS research director - autonomous lab orchestration for LLM security research."
        ),
        "owner": {"name": "AEGIS (poc_medical)"},
        "plugins": [
            {
                "name": PLUGIN_NAME,
                "version": PLUGIN_VERSION,
                "description": "Autonomous research director: OODA loop, safety floor, 9 core skills.",
                "source": "./",
                "category": "research",
                "tags": ["research", "orchestration", "llm-security", "ooda", "aegis"],
            }
        ],
    }
    (PLUGIN_DIR / "marketplace.json").write_text(
        json.dumps(market, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def write_build_info() -> None:
    """Drop a build note in `.claude-plugin/` (a dir not scanned for skills/commands)."""
    note = (
        BANNER
        + "\n# OMC-AEGIS plugin - generated tree\n\n"
        "`skills/`, `commands/` and the two manifests here are GENERATED from\n"
        "`.claude/skills/` by `scripts/build_omc_plugin.py`.\n\n"
        "- Source of truth: `.claude/skills/<name>/`\n"
        "- Regenerate: `python scripts/build_omc_plugin.py`\n"
        "- Scope: " + ", ".join(CORE_SKILLS) + "\n"
    )
    (PLUGIN_DIR / "BUILD_INFO.md").write_text(note, encoding="utf-8")


def main() -> None:
    print("Building plugin '" + PLUGIN_NAME + "' v" + PLUGIN_VERSION + " from " + str(SKILLS_SRC))
    SKILLS_OUT.mkdir(parents=True, exist_ok=True)
    COMMANDS_OUT.mkdir(parents=True, exist_ok=True)
    PLUGIN_DIR.mkdir(parents=True, exist_ok=True)
    for name in CORE_SKILLS:
        copy_skill(name)
        write_command_shim(name)
    write_plugin_json()
    write_marketplace_json()
    write_build_info()
    print(
        "\nDone. "
        + str(len(CORE_SKILLS))
        + " skills, "
        + str(len(CORE_SKILLS))
        + " command shims, 2 manifests."
    )
    print("  skills/         -> " + str(SKILLS_OUT))
    print("  commands/       -> " + str(COMMANDS_OUT))
    print("  .claude-plugin/ -> " + str(PLUGIN_DIR))


if __name__ == "__main__":
    main()
